import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Navbar } from './navbar';
import './globals.css';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col bg-background text-foreground">
          <main className="flex-1 overflow-y-auto">{children}</main>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
