import { DefaultTheme } from 'styled-components';

export const lightTheme: DefaultTheme = {
  background: '#FFFFFF',
  borderRadius: '0.5rem',
  text: '#151A2E',
  textSecondary: '#151A2E50',
  overlay: 'hsla(0, 0%, 100%, 0.5)',
  shadow: 'hsla(0, 0%, 0%, 0.25)',
  navbar: '#FFD904',
  buttonText: '#FAFAFA',
  primary: '#E3000A',
  buttonPrimaryHover: '#16998b',
  buttonPrimaryDisabled: '#0e635a',
  fontFamily: `'Montserrat', sans-serif`,
  fontFamilySecondary: `'Fira Code', monospace`,
  fontSizeXxxs: '0.65rem',
  fontSizeXxs: '0.75rem',
  fontSizeXs: '0.8125rem',
  fontSizeSm: '0.875rem',
  fontSizeMd: '1rem',
  fontSizeLg: '1.25rem',
  fontSizeXl: '1.5rem',
  fontSizeXxl: '2rem',
  fontSizeXxxl: '4rem',
  fontWeightLight: '300',
  fontWeightRegular: '400',
  fontWeightMedium: '500',
  fontWeightSemiBold: '600',
  fontWeightBold: '700',
  fontWeightExtraBold: '800',
  fontWeightBlack: '900',
  transition: 'all 150ms ease-in-out',
};
